
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [8]:
import numpy as np

array_1d = np.arange(9)
print(array_1d)

[0 1 2 3 4 5 6 7 8]


Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [9]:
# Reshape the 1D array into a 3x3 matrix

array_2d = array_1d.reshape(3, 3)

print("\nReshaped 3x3 matrix:")

print(array_2d)


Reshaped 3x3 matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Access the element at the second row, second column.


In [10]:
element = array_2d[1, 1]  # Indices start from 0, so row 2 is index 1, and column 2 is index 1
print("Element at the second row, second column:", element)

Element at the second row, second column: 4


Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [11]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Element-wise addition
addition = array1 + array2

# Element-wise subtraction
subtraction = array1 - array2

# Element-wise multiplication
multiplication = array1 * array2

# Element-wise division
division = array1 / array2

# Print the results
print("Element-wise addition:", addition)
print("Element-wise subtraction:", subtraction)
print("Element-wise multiplication:", multiplication)
print("Element-wise division:", division)

Element-wise addition: [5 7 9]
Element-wise subtraction: [-3 -3 -3]
Element-wise multiplication: [ 4 10 18]
Element-wise division: [0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [12]:
array = np.array([1, 2, 3, 4, 5])

# Calculate the sum
array_sum = np.sum(array)

# Calculate the mean
array_mean = np.mean(array)

# Calculate the standard deviation
array_std = np.std(array)

# Print the results
print("Sum:", array_sum)
print("Mean:", array_mean)
print("Standard Deviation:", array_std)

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [14]:
array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2x3 matrix
reshaped_array = array.reshape(2, 3)

# Print the reshaped array
print(f"Reshaped 2x3 array:\n{reshaped_array}")

Reshaped 2x3 array:
[[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [15]:
# Create a 5x5 array with random integers between 0 and 100
array_5x5 = np.random.randint(0, 100, size=(5, 5))

# Print the array
print("5x5 array with random integers:")
print(array_5x5)

5x5 array with random integers:
[[97 54 87 43 60]
 [78 42  4 28 84]
 [24 95  4 17 52]
 [ 2 97 30 14 62]
 [35 20 99 18 93]]


Replace all values in the sub-array with a specific value.


In [16]:
# Define the specific value to replace with
specific_value = -1

# Replace all values in the sub-array (e.g., the 2x2 sub-array in the top-left corner)
# We can define any sub-array range here. For example, replacing a 2x2 sub-array starting at the top-left corner:
array_5x5[0:2, 0:2] = specific_value

print("\n5x5 array after replacing sub-array values with specific value:")
print(array_5x5)


5x5 array after replacing sub-array values with specific value:
[[-1 -1 87 43 60]
 [-1 -1  4 28 84]
 [24 95  4 17 52]
 [ 2 97 30 14 62]
 [35 20 99 18 93]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [17]:
original_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

# Extract the subarray [[3, 4], [7, 8]]
subarray = original_array[[1, 3], :]

# Print the extracted subarray
print("Extracted subarray:")
print(subarray)

Extracted subarray:
[[3 4]
 [7 8]]



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [18]:
one_d_array = np.arange(3)

# Use broadcasting to create a 2D array of shape (3, 3)
two_d_array = np.tile(one_d_array, (3, 1))

# Print the 2D array
print("2D array of shape (3, 3) with values from 0 to 2:")
print(two_d_array)

2D array of shape (3, 3) with values from 0 to 2:
[[0 1 2]
 [0 1 2]
 [0 1 2]]


Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [21]:
# Create a 2D array of shape (3, 3) with values from 0 to 2
two_d_array = np.tile(np.arange(3), (3, 1))

# Create a 1D array of shape (3,)
one_d_array = np.array([1, 2, 3])

# Use broadcasting to add the 1D array to each row of the 2D array
result_array = two_d_array + one_d_array

# Print the result
print("Resultant 2D array after broadcasting:")
print(result_array)

Resultant 2D array after broadcasting:
[[1 3 5]
 [1 3 5]
 [1 3 5]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [22]:
# Create two 2D arrays of shape (3, 3) with random integers
array1 = np.random.randint(0, 100, size=(3, 3))
array2 = np.random.randint(0, 100, size=(3, 3))

# Print the results
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

Array 1:
[[44 52 21]
 [53 27 52]
 [ 6 83 76]]

Array 2:
[[99  4 62]
 [58  3  4]
 [69 83 40]]


In [23]:
# Concatenate them horizontally
concatenated_horizontal = np.concatenate((array1, array2), axis=1)

# Concatenate them vertically
concatenated_vertical = np.concatenate((array1, array2), axis=0)


print("\nConcatenated horizontally:")
print(concatenated_horizontal)

print("\nConcatenated vertically:")
print(concatenated_vertical)


Concatenated horizontally:
[[44 52 21 99  4 62]
 [53 27 52 58  3  4]
 [ 6 83 76 69 83 40]]

Concatenated vertically:
[[44 52 21]
 [53 27 52]
 [ 6 83 76]
 [99  4 62]
 [58  3  4]
 [69 83 40]]


In [25]:
# Split the concatenated arrays back into the original arrays
split_horizontal = np.hsplit(concatenated_horizontal, 2)
split_vertical = np.vsplit(concatenated_vertical, 2)

print("\nSplit horizontally:")
print(split_horizontal)

print("\nSplit vertically:")
print(split_vertical)


Split horizontally:
[array([[44, 52, 21],
       [53, 27, 52],
       [ 6, 83, 76]]), array([[99,  4, 62],
       [58,  3,  4],
       [69, 83, 40]])]

Split vertically:
[array([[44, 52, 21],
       [53, 27, 52],
       [ 6, 83, 76]]), array([[99,  4, 62],
       [58,  3,  4],
       [69, 83, 40]])]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [27]:
arr = [1, 2, 1, 2, 3, 4, 5, 6, 8, 9, 1, 2, 2, 22, 21, 1, 1, 1, 1, 2, 5]

# Initialize variables to keep track of mode and its count
mode = None
max_count = 0

# Loop through each unique element in the array
for num in set(arr):
    # Count the occurrences of the current element in the array
    count = arr.count(num)
    # If the current count is greater than the maximum count so far, update mode and max_count
    if count > max_count:
        max_count = count
        mode = num

print("Mode of the array:", mode)

Mode of the array: 1


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

